services:
  db:
    image: postgres:15.0-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - trading_results-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_results_app
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    networks:
      - trading_results-network

  redis:
    image: redis:7.2
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - ./.env
    volumes:
      - redis-data:/data
    networks:
      - trading_results-network

volumes:
  redis-data:
  postgres_data:

networks:
  trading_results-network:
    driver: bridge
